# Generated by Django 4.1 on 2024-04-11 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AGV',
            fields=[
                ('vehicle_id', models.IntegerField(primary_key=True, serialize=False)),
                ('vehicle_model', models.CharField(blank=True, max_length=255)),
                ('maximum_battery', models.IntegerField(default=0)),
                ('maximum_velocity', models.IntegerField(default=0)),
                ('guidance_type', models.CharField(blank=True, choices=[('OPT', 'Optical Tape'), ('MAG', 'Magnetic Tape'), ('WIR', 'Wire Guided'), ('LZR', 'Laser Guided')], max_length=255)),
                ('loading_type', models.CharField(choices=[('AUTO', 'Automatic'), ('MAN', 'Manual')], max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_connected', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AGV_data',
            fields=[
                ('data_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('car_id', models.IntegerField()),
                ('carSpeed', models.IntegerField()),
                ('previousNode', models.IntegerField()),
                ('nextNode', models.IntegerField()),
                ('carBattery', models.IntegerField()),
                ('carState', models.IntegerField()),
                ('carObstac', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='AGVStates',
            fields=[
                ('state_id', models.IntegerField(primary_key=True, serialize=False)),
                ('carState', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DataSchedule',
            fields=[
                ('schedule_id', models.IntegerField(primary_key=True, serialize=False)),
                ('order_date', models.DateTimeField()),
                ('order_number_id', models.IntegerField()),
                ('load_name', models.CharField(default='Metal', max_length=255)),
                ('load_weight', models.IntegerField(default=25)),
                ('car_id', models.IntegerField()),
                ('est_start_time', models.TimeField()),
                ('est_end_time', models.TimeField()),
                ('begin_node', models.IntegerField()),
                ('destination_node', models.IntegerField()),
                ('est_distance', models.IntegerField()),
                ('est_energy', models.IntegerField(default=0)),
                ('is_complete', models.BooleanField(default=False)),
            ],
        ),
    ]
