# Generated by Django 4.1 on 2024-04-18 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageAGV', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DB_StationData',
            fields=[
                ('station_id', models.IntegerField(primary_key=True, serialize=False)),
                ('station_node', models.IntegerField(default=0)),
                ('station_type', models.CharField(blank=True, choices=[('HOME', 'Parking station'), ('BAT', 'Charging station'), ('PICK', 'Pick up'), ('DROP', 'Drop')], max_length=64)),
                ('load_transfer', models.CharField(blank=True, choices=[('AUTO', 'Automatic'), ('MAN', 'Manual')], max_length=64)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='orderData',
            fields=[
                ('request_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('orderDate', models.DateTimeField(blank=True)),
                ('orderNumber', models.IntegerField(default=0)),
                ('loadName', models.CharField(default='Metal', max_length=255)),
                ('load_weight', models.IntegerField(default=25)),
                ('start_time', models.CharField(default='00:00', max_length=255)),
                ('startPoint', models.IntegerField(default=0)),
                ('endPoint', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='dataschedule',
            name='est_end_time',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='dataschedule',
            name='est_start_time',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='dataschedule',
            name='order_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
