# Generated by Django 4.1 on 2024-04-19 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageAGV', '0003_alter_agv_data_data_id_alter_agvstates_state_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agv',
            name='vehicle_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
