# Generated by Django 4.1 on 2024-04-19 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageAGV', '0004_alter_agv_vehicle_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdata',
            name='isExecute',
            field=models.BooleanField(default=False),
        ),
    ]
